name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci

      - name: Add Cloudflare env
        run: |-
          touch .env
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" >> .env

      - name: Deploy worker
        run: npm run deploy